iox-#2330 Update ExecStart path and improve service start feedback
Changed the ExecStart path in the systemd unit file to /usr/local/bin/iox-roudi for better alignment with executable location. Added log output for failed service start attempts to aid in debugging.

diff --git a/.github/workflows/build_systemd.yaml b/.github/workflows/build_systemd.yaml
--- a/.github/workflows/build_systemd.yaml
+++ b/.github/workflows/build_systemd.yaml
@@ -29,7 +29,7 @@ jobs:
       - name: Ldconfig run
         run: sudo  ldconfig
       - name: Create unit file
-        run: echo -e "[Unit]\nDescription=Test application roudi\n\n[Service]\nType=notify\nUser=roma\nRestartSec=10\nRestart=always\nExecStart=/usr/bin/iox-roudi\nTimeoutStartSec=10\nWatchdogSec=5\n\n[Install]\nWantedBy=multi-user.target" | sudo tee /usr/lib/systemd/system/test_iox.service > /dev/null
+        run: echo -e "[Unit]\nDescription=Test application roudi\n\n[Service]\nType=notify\nUser=roma\nRestartSec=10\nRestart=always\nExecStart=/usr/local/bin/iox-roudi\nTimeoutStartSec=10\nWatchdogSec=5\n\n[Install]\nWantedBy=multi-user.target" | sudo tee /usr/lib/systemd/system/test_iox.service > /dev/null
       - name: Show unit
         run: cat /usr/lib/systemd/system/test_iox.service
       - name: Daemon reload
@@ -37,6 +37,7 @@ jobs:
       - name: Check status
         run: sudo systemctl status test_iox || true
       - name: Start roudi
-        run: sudo systemctl start test_iox
+        run: |
+          sudo systemctl start test_iox || (echo "Failed to start service"; sudo journalctl -u test_iox -n 50)
       - name: Stop roudi
         run: sudo systemctl stop test_iox
